### ISSUE TITLE
dev-db/firebird-3.0.0.32136_rc1

### ISSUE THREAD

**Issue by linuxunderground** [Obsidian-StudiosInc/os-xtoo#1]
Hi,

I tried your firebird (rc1) ebuild but it does not work.
I'm searching a solution also but I don't find...

In attachment, build.log :
[build.zip](https://github.com/Obsidian-StudiosInc/os-xtoo/files/90301/build.zip)

Kind regards.

Vincent.

**Comment by wltjr** [comment]
The failure is pretty strange, looks like it could not turn forced writes off or something. I do not see any compile failures. It seems to fail at this point

creating database ../../gen/examples/employee.fdb
Turning forced writes off
Couldn't turn forced writes off
Makefile.examples:125: recipe for target '../../gen/examples/employee.fdb' failed

I have a feeling employee.fdb was created, you can look in portage temp space, under the work directory. Maybe something in the build env causing the forced writes to fail.

Looks to be here -> https://github.com/asfernandes/firebird/blob/master/examples/empbuild/empbuild.e
Lines 96-100

printf ("Turning forced writes off\n");
sprintf (cmd, "gfix -write async %s", Db_name);
if (system (cmd))
    {
    printf ("Couldn't turn forced writes off\n");
    exit (FINI_ERROR);
    }

I would assume this is a build env issue, possibly specific to your system or build env. I have built this on a few systems and haven't run into that myself. It would not have anything to do with the ebuild itself. Not something I can change in the ebuild to address that issue. It may be an upstream bug, but I would imagine others to run into this. Looks like that code has been as is for some time, not new code.

**Comment by wltjr** [comment]
Going to close this as I cannot replicate, and not sure I can fix this in the ebuild. You might try to build firebird outside of portage and see if you have the same error. Thinking it might be system specific, some reason why forced writes could not be turned off.

**Comment by linuxunderground** [comment]
FYI :

Outside of portage, Firebird build is OK !

Vincent

2016-02-19 16:55 GMT+01:00 William L. Thomson Jr. notifications@github.com
:

**Comment by wltjr** [comment]
Very strange, I would love to be able to replicate this myself.. I can re-open. I take it that it still fails within portage?

**Comment by wltjr** [comment]
What is your emerge --info, have you added any options to FEATURES? Wondering if something is going on in your sandbox. Are you running hardened? Might check dmesg to see if anything was killed. Though doubt that is the case. Must be some reason why turning off writes is failing.

**Comment by linuxunderground** [comment]
FEATURES is equal to default value.
emerge --info in attachment...

2016-02-19 20:32 GMT+01:00 William L. Thomson Jr. notifications@github.com
:

> What is your emerge --info, have you added any options to FEATURES?
> Wondering if something is going on in your sandbox. Are you running
> hardened? Might check dmesg to see if anything was killed. Though doubt
> that is the case. Must be some reason why turning off writes is failing.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Obsidian-StudiosInc/os-xtoo/issues/1#issuecomment-186370104
> .

# Portage 2.2.27 (python 3.4.3-final-0, default/linux/amd64/13.0, gcc-4.9.3, glibc-2.21-r2, 4.1.9-gentoo-r1 x86_64)

System uname: Linux-4.1.9-gentoo-r1-x86_64-Intel-R-_Xeon-R-_CPU_X3323_@_2.50GHz-with-gentoo-2.2
KiB Mem:     4187028 total,   3553348 free
KiB Swap:    4008212 total,   4008212 free
Timestamp of repository gentoo: Thu, 18 Feb 2016 11:15:01 +0000
sh bash 4.3_p42-r1
ld GNU ld (Gentoo 2.25.1 p1.1) 2.25.1
ccache version 3.1.9 [disabled]
app-shells/bash:          4.3_p42-r1::gentoo
dev-java/java-config:     2.2.0::gentoo
dev-lang/perl:            5.20.2::gentoo
dev-lang/python:          2.7.10-r1::gentoo, 3.3.5-r2::gentoo, 3.4.3-r1::gentoo
dev-util/ccache:          3.1.9-r4::gentoo
dev-util/cmake:           3.3.1-r1::gentoo
dev-util/pkgconfig:       0.28-r2::gentoo
sys-apps/baselayout:      2.2::gentoo
sys-apps/openrc:          0.19.1::gentoo
sys-apps/sandbox:         2.10-r1::gentoo
sys-devel/autoconf:       2.13::gentoo, 2.69::gentoo
sys-devel/automake:       1.11.6::gentoo, 1.14.1::gentoo, 1.15::gentoo
sys-devel/binutils:       2.25.1-r1::gentoo
sys-devel/gcc:            4.9.3::gentoo, 5.3.0::gentoo
sys-devel/gcc-config:     1.7.3::gentoo
sys-devel/libtool:        2.4.6::gentoo
sys-devel/make:           4.1-r1::gentoo
sys-kernel/linux-headers: 4.3::gentoo (virtual/os-headers)
sys-libs/glibc:           2.21-r2::gentoo
Repositories:

gentoo
    location: /usr/portage
    sync-type: rsync
    sync-uri: rsync://rsync1.fr.gentoo.org/gentoo-portage
    priority: -1000

linuxunderground-overlay
    location: /usr/local/linuxunderground-overlay
    masters: gentoo
    priority: 0

ACCEPT_KEYWORDS="amd64"
ACCEPT_LICENSE="\* -@EULA"
CBUILD="x86_64-pc-linux-gnu"
CFLAGS="-march=nocona -O2 -pipe"
CHOST="x86_64-pc-linux-gnu"
CONFIG_PROTECT="/etc /usr/share/config /usr/share/gnupg/qualified.txt"
CONFIG_PROTECT_MASK="/etc/ca-certificates.conf /etc/dconf /etc/env.d /etc/fonts/fonts.conf /etc/gconf /etc/gentoo-release /etc/php/apache2-php5.4/ext-active/ /etc/php/apache2-php5.6/ext-active/ /etc/php/cgi-php5.4/ext-active/ /etc/php/cgi-php5.6/ext-active/ /etc/php/cli-php5.4/ext-active/ /etc/php/cli-php5.6/ext-active/ /etc/revdep-rebuild /etc/sandbox.d /etc/terminfo"
CXXFLAGS="-march=nocona -O2 -pipe"
DISTDIR="/mnt/sauvegardes2/hrd/gentoo/distfiles"
FCFLAGS="-O2 -pipe"
FEATURES="assume-digests binpkg-logs config-protect-if-modified distlocks ebuild-locks fixlafiles merge-sync news parallel-fetch preserve-libs protect-owned sandbox sfperms strict unknown-features-warn unmerge-logs unmerge-orphans userfetch userpriv usersandbox usersync xattr"
FFLAGS="-O2 -pipe"
GENTOO_MIRRORS="http://mirror.ovh.net/gentoo-distfiles/"
LANG="fr_BE.UTF-8"
LDFLAGS="-Wl,-O1 -Wl,--as-needed"
MAKEOPTS="-j2"
PKGDIR="/usr/portage/packages"
PORTAGE_CONFIGROOT="/"
PORTAGE_RSYNC_OPTS="--recursive --links --safe-links --perms --times --omit-dir-times --compress --force --whole-file --delete --stats --human-readable --timeout=180 --exclude=/distfiles --exclude=/local --exclude=/packages --exclude=/.git"
PORTAGE_TMPDIR="/var/tmp"
USE="X acl alsa amd64 apache2 avi berkdb bzip2 cli consolekit corefont cracklib crypt cups cxx dbus dri dvd encode faac fortran freerdp gd gdbm gif gudev iconv icu ipv6 java jpeg kde kerberos lame minizip mmx mmxext modules mp3 mpeg multilib ncurses nls nptl nsplugins ogg opengl openmp pam pcre pcsc-lite pkcs11 png policykit ppds python qt-faststart qt3support qt4 readline samba seccomp session sqlite sse sse2 ssl svg tcpd theora tiff truetype udev unicode usb vmware vorbis vpx webkit winbind x264 xattr xcomposite xml xorg zlib" ABI_X86="64 32" ALSA_CARDS="ali5451 als4000 atiixp atiixp-modem bt87x ca0106 cmipci emu10k1x ens1370 ens1371 es1938 es1968 fm801 hda-intel intel8x0 intel8x0m maestro3 trident usb-audio via82xx via82xx-modem ymfpci" APACHE2_MODULES="authn_core authz_core socache_shmcb unixd actions alias auth_basic authn_alias authn_anon authn_dbm authn_default authn_file authz_dbm authz_default authz_groupfile authz_host authz_owner authz_user autoindex cache cgi cgid dav dav_fs dav_lock deflate dir disk_cache env expires ext_filter file_cache filter headers include info log_config logio mem_cache mime mime_magic negotiation rewrite setenvif speling status unique_id userdir usertrack vhost_alias" APACHE2_MPMS="worker" CALLIGRA_FEATURES="kexi words flow plan sheets stage tables krita karbon braindump author" CAMERAS="ptp2" COLLECTD_PLUGINS="df interface irq load memory rrdtool swap syslog" CPU_FLAGS_X86="mmx mmxext sse sse2" ELIBC="glibc" GPSD_PROTOCOLS="ashtech aivdm earthmate evermore fv18 garmin garmintxt gpsclock itrax mtk3301 nmea ntrip navcom oceanserver oldstyle oncore rtcm104v2 rtcm104v3 sirf superstar2 timing tsip tripmate tnt ublox ubx" INPUT_DEVICES="vmmouse keyboard evdev" KERNEL="linux" LCD_DEVICES="bayrad cfontz cfontz633 glk hd44780 lb216 lcdm001 mtxorb ncurses text" LIBREOFFICE_EXTENSIONS="presenter-console presenter-minimizer" LINGUAS="fr en" OFFICE_IMPLEMENTATION="libreoffice" PHP_TARGETS="php5-5" PYTHON_SINGLE_TARGET="python3_4" PYTHON_TARGETS="python2_7 python3_4" QEMU_USER_TARGETS="arm armeb" RUBY_TARGETS="ruby20 ruby21" USERLAND="GNU" VIDEO_CARDS="vmware" XTABLES_ADDONS="quota2 psd pknock lscan length2 ipv4options ipset ipp2p iface geoip fuzzy condition tee tarpit sysrq steal rawnat logmark ipmark dhcpmac delude chaos account"
Unset:  CC, CPPFLAGS, CTARGET, CXX, EMERGE_DEFAULT_OPTS, INSTALL_MASK, LC_ALL, PORTAGE_BUNZIP2_COMMAND, PORTAGE_COMPRESS, PORTAGE_COMPRESS_FLAGS, PORTAGE_RSYNC_EXTRA_OPTS, USE_PYTHON

**Comment by linuxunderground** [comment]
In attachment, emerge --info from an old x86 PC where Firebird build works
well.

2016-02-19 20:32 GMT+01:00 William L. Thomson Jr. notifications@github.com
:

**Comment by linuxunderground** [comment]
missing attachment for my last post

**Comment by linuxunderground** [comment]
SOLVED :

CFLAGS in my /etc/portage/make.conf :

CFLAGS="-march=nocona -O2 -pipe" : failure
CFLAGS="-march=nocona -O1 -pipe" : failure
CFLAGS="-march=nocona -O0 -pipe" : OK it works

2016-02-19 20:32 GMT+01:00 William L. Thomson Jr. notifications@github.com
:

**Comment by wltjr** [comment]
That is really odd, I thought it might have something to do with that, but yours were similar to mine. Might be something to report to upstream as a bug. Not sure the change of optimization should cause turning off force writes to fail.

I have

CFLAGS="-march=x86-64 -mcx16 -msahf -mpopcnt -O2 -pipe"

And on another

CFLAGS="-O2 -pipe -march=amdfam10 -mcx16 -msahf -mabm -mlzcnt

I came across this sometime back for extra flags :)
http://gentoo-what-did-you-say.blogspot.com/2011/07/finding-cpu-flags-using-gcc.html

I am glad you found the problem, sorry I was not more help. Still think its pretty odd!

**Comment by linuxunderground** [comment]
Many thanks for the link about cpu-flags.

But no better optimization possible with core2 flag :
CFLAGS="-march=core2 -O0 -pipe"

2016-02-21 17:19 GMT+01:00 William L. Thomson Jr. notifications@github.com
:

**Comment by wltjr** [comment]
Sure thing, here are some more. You can always set that for a given package and not have to change it globally.

https://wiki.gentoo.org/wiki//etc/portage/package.env
https://wiki.gentoo.org/wiki/Knowledge_Base:Overriding_environment_variables_per_package

Wonder if its a gcc issue or something. Its really strange that changing optimization causes and issue.

**Comment by linuxunderground** [comment]
Building with CFLAGS="-march=core2 -O3 -pipe -fno-omit-frame-pointer" works fine !

It seems frame-pointer generation is required for Firebird build.
After some googling, frame-pointer default option varies depending on the platform (and perhaps also based on gcc version?).

Ebuild should always force -fno-omit-frame-pointer. This is also consistent with the default optimization flags defined in Firebird tarball archive.

**Comment by wltjr** [comment]
Ok I will see about adding that. Seems it was lost in the past years efforts to drop package specified cflags in place of user ones on Gentoo. But has some side effects, which this is one. Thanks for your effort on this, since I could not replicate, made it really hard to trouble shoot. Though I bet I can now knowing the issue...

**Comment by wltjr** [comment]
Ok I made the changes https://github.com/Obsidian-StudiosInc/os-xtoo/commit/8ca010dc6a5b7e21f8b4789de1f0128088ee76a0

Still merges fine for me, so this should correct the issue if those flags are not set properly. Not sure if replace would handle things correctly if the flag is not set. Think doing a check if the flag is set is a bit over kill. If it is not there filter will do nothing, and append will add it. Though if its there already I guess it will be added twice, unless append checks such. Either way should be resolved if not the most elegant solution.
