### ISSUE TITLE
dev-java/guava-23.3 fails to compile

### ISSUE THREAD

**Issue by fordfrog** [Obsidian-StudiosInc/os-xtoo#16]
with jdk-1.8 it ends up with this:

javac: invalid flag: --release

with jdk-1.9 it ends up with bunch of errors because jdk-1.9 does not contain sun.misc package which guava uses.

**Comment by wltjr** [comment]
Packages need additional options for Java 9. Things you will run into. I have made a [cheat sheet](https://github.com/Obsidian-StudiosInc/java9-cheat-sheet) to aid.

**Comment by wltjr** [comment]
You mentioned in irc 23.5 failing. If that did fail please provide the build.log. Providing your using JDK 9. It did not fail here. Curious what caused a failure for you. Thanks!

**Comment by wltjr** [comment]
Closing as all build issues with guava should be resolved. Feel free to re-open or file again if problem remains. Thank you!
