### ISSUE TITLE
Demo DataBase

### ISSUE THREAD

**Issue by linuxunderground** [Obsidian-StudiosInc/os-xtoo#2]
Since the old .fdb files are no longer compatible with the new .fdb ([http://tracker.firebirdsql.org/browse/CORE-5003?page=com.atlassian.jira.plugin.system.issuetabpanels:changehistory-tabpanel](url)), it would be nice to install the demo DataBase.

For this, I propose this patch for your ebuild :
[FB3-employee_fdb.zip](https://github.com/Obsidian-StudiosInc/os-xtoo/files/146375/FB3-employee_fdb.zip)

**Comment by wltjr** [comment]
Ok thanks I will add that. If you can please fork the repository, and send over pull requests to merge in such patches. Bit nicer way of collaborating.

**Comment by wltjr** [comment]
I added your patch with a few improvements/tweaks. https://github.com/Obsidian-StudiosInc/os-xtoo/commit/4bdc67697972821b58a8af71f9bdcd686e0d5c8a
