### ISSUE TITLE
net-misc/econnman-1.1: missing dev-python/python-efl dependency

### ISSUE THREAD

**Issue by tbart** [Obsidian-StudiosInc/os-xtoo#23]
The title speaks for itself, but here is a diff as well:

```
--- econnman-1.1.ebuild	2018-02-05 12:06:47.516998343 +0100
+++ econnman-1.1-r1.ebuild	2018-02-05 22:56:26.493043087 +0100
@@ -17,6 +17,7 @@
 RDEPEND="
 	dev-libs/efl
 	net-misc/connman
+	dev-python/python-efl
 "
 
 DEPEND="${RDEPEND}"
```

**Comment by wltjr** [comment]
Ok thanks I will correct ASAP. Please let me know if you find other issues. I do not use econnman myself. I use NetworkManager and the gnome nm-applet. Till I get a chance to make a NM module for E. Though others keep telling me they are working on such. Only aware of [oconnection}(https://github.com/eyoz/oconnection) and no clue as to its state, usable, etc.

**Comment by wltjr** [comment]
Are you sure it needs python-efl, or some other? I though econnonman came from intel. Or is it the stuff in E that needs python-efl for econnman? Just curious as I do not use. Thanks

**Comment by wltjr** [comment]
Not sure this was the correct place for the dependency. Not sure econnman needs that. Seems like it should be a dependency of enlightenment when econnman/wifi module is activated via USE. I may experiment a bit, but I think that is what you are after. Econnman itself should not need any EFL or python-efl.

**Comment by tbart** [comment]
Well it's a little confusing.
Enlightenment itself has a module called connman. That one works without python-efl. But it just shows a connection in the systray. That's all. All the rest has to be done in connman config/cli. And yes, connman itself is by intel.
Econnman extends the systray icon with a "settings" option, so you can configure connman directly from within E.
And clicking on settings produces a crash message without python-efl. So I guess it should be okay like this.

**Comment by tbart** [comment]
(btw: I think NM does not really fit into the E philosophy of being small/low footprint. Connman fits this bill much better. And apart from tagged VLANs I think it can do most everything a desktop user needs: ethernet/wifi/tethering/VPN, proper failovers, one connection active etc.)

**Comment by wltjr** [comment]
Yeah I was confusing connman with econnman. Thank you for explaining that, as I haven't ever used it. Please let me know if there are other changes needed for that. I added some of those deps under wifi USE flag. But I never tested, as I did not want to mess with my NM config, etc.

You are correct about connman footprint, and being preferred by E. I believe it also goes as far as Tizen as well. Though at the same time they use Systemd, so.... That is not really light weight per se. The main thing connman lacked I need is up/down hooks. To like mount nfs shares, ntp,  start synergy, and other stuff like that. Seem to recall that it may get such someday.

Thanks again for testing it out and reporting the missing dep!
