### ISSUE TITLE
x11-wm/enlightenment: missing acpi use flag/dependency

### ISSUE THREAD

**Issue by tbart** [Obsidian-StudiosInc/os-xtoo#24]
Also see https://bugs.gentoo.org/637034

Suspend, standby (at least, probably more) does not work without acpid.
```
--- enlightenment-0.22.1.ebuild	2018-02-05 12:06:47.520998343 +0100
+++ enlightenment-0.22.1-r1.ebuild	2018-02-05 23:01:34.701030448 +0100
@@ -42,7 +42,7 @@
 	${__NORM_MODS[@]/#/enlightenment_modules_}
 )
 
-IUSE="bluetooth connman doc egl nls pam spell static-libs systemd udisks
+IUSE="acpi bluetooth connman doc egl nls pam spell static-libs systemd udisks
 	wayland wifi ${IUSE_E_MODULES[@]/#/+}"
 
 REQUIRED_USE="
@@ -52,6 +52,7 @@
 "
 
 DEPEND="
+	acpi ( sys-power/acpid )
 	bluetooth? ( net-wireless/bluez )
 	connman? ( net-misc/econnman )
 	pam? ( sys-libs/pam )
```

**Comment by wltjr** [comment]
Thanks I was pulling it in directly, likely does need to be a dep. I need to double check to make sure no enable/disable build options for such. I don't see any in [meson_options](https://github.com/Enlightenment/enlightenment/blob/master/meson_options.txt). Looks like just missing the dep. Thanks!

**Comment by wltjr** [comment]
FYI your depend was a tad off missing the question mark after the USE flag  ```acpi? ( sys-power/acpid )```

**Comment by tbart** [comment]
Absolutely, just noticed and came back to correct it.. Thanks!
