### ISSUE TITLE
dev-db/firebird-3.0.0.32136_rc1 : only root

### ISSUE THREAD

**Issue by linuxunderground** [Obsidian-StudiosInc/os-xtoo#3]
I can use Firebird 3 but I can open a Firebird database only with user root and not with a normal user.

**Comment by wltjr** [comment]
How are you trying to open a database?

**Comment by linuxunderground** [comment]
With a simple Python script :
https://462484.bugs.gentoo.org/attachment.cgi?id=394722

emerge dev-python/fdb

ebuild ->
https://github.com/linuxunderground/gentoo.overlay/tree/master/dev-python/fdb

2016-03-09 18:18 GMT+01:00 William L. Thomson Jr. notifications@github.com
:

**Comment by wltjr** [comment]
Did you create the SYSDBA user with the masterkey password? Are you using legacy or SRP authentication with Firebird 3? Users and passwords are managed completely different on Firebird 3, and by default there is no SYSDBA user unless you create one. Thus asking if you created that or not.

**Comment by linuxunderground** [comment]
New users and passwords management of FB3 is a bit confusing for me.

I does not create SYSDBA user and I kept default config files :-s

2016-03-10 21:34 GMT+01:00 William L. Thomson Jr. notifications@github.com
:

**Comment by wltjr** [comment]
I am still trying to grasp it all myself. I have read the release notes a few times, and I recommend them. You pretty much have to read them to get SYSDBA working again and other stuff as it used to. Much less moving to how the new stuff workds, which I have yet. You can have users stored in databases vs security3.fdb. There is lots of flexibility and different models in FB3, its way different.

Which FB uses a new security3.fdb, so anything from previous does not matter or get used. I was not able to find out how legacy mode can support security2.fdb, and I do not think it does. I think legacy mode uses security3.fdb for users vs in the database files themselves. When going from security.fdb -> secrurity2.fdb, they provided a .sql script to run for the conversion. But such does not exit for security2.fdb -> security3.fdb. I need to redo the whole pkg_config section, or at least the part about security*.fdb.

There might be a way to migrate users and stuff from FB 2.x to FB3 via the ebuild. But that would likely carry them on to doing things the legacy way. I am not sure I would want to force such, though I guess could be the option. However if people switch to storing user accounts within database, which might be better anyway. Carrying forward the old way would not be good, and better to not give people the option to force them to use newer ways. Hard call, but work needs to be done either way to support migrating users and preserving legacy function.

Also gsec is very different in Firebird 3, as you cannot add/manage users when databases are running and/or in use. I have had lots of issues with that. I am not able to use Flamerobin to manage users either, which is interesting. I was able to do that before. I assume Flamerobin will be updated at some point to allow such. User management thus far on FB3 has been pretty difficult. I need to revisit it all and get more familiar with it. Though I do have FB3 running in production and development. Just need to mess with managing users more and moving off legacy function.

**Comment by wltjr** [comment]
Here is link. Also new rc2 updating ebuild now.  I will see about adding to docs. http://web.firebirdsql.org/download/prerelease/rlsnotes/Firebird-3.0.0_RC2-ReleaseNotes.pdf

**Comment by linuxunderground** [comment]
Thanks a lot for all your informations :-)

2016-03-11 20:01 GMT+01:00 William L. Thomson Jr. notifications@github.com
:

**Comment by wltjr** [comment]
Your welcome, just added rc2 and the release notes get installed with docs USE flag now.

**Comment by wltjr** [comment]
Going to close this as well, I think it was an issue with FB 3 changes not the package itself or ebuild.
