### ISSUE TITLE
The efl ebuild misses libraw dependency

### ISSUE THREAD

**Issue by kanyck** [Obsidian-StudiosInc/os-xtoo#39]
Somewhat like
`rawphoto? ( media-libs/libraw )`
is probably needed. Now it fails to build without libraw installed...

**Comment by wltjr** [comment]
Thanks for the report, looking into that now. It seems like it is not an optional thing, if your build is failing. Though maybe enabled by default or something else is triggering it. If it is needed all the time, a USE flag would not make sense.

I just checked and I do not have libraw installed. Where are you getting this failure? Can you provide your build.log? What USE flags are you building EFL with? Maybe something triggering that or needs that. Are you using live ebuild or 1.20.7? I haven't tested live for a bit. Tend to avoid git E stuff.

**Comment by kanyck** [comment]
You won't see the bug until rawphoto USE flag is set. But if you do, build will fail without libraw installed.
[build.log](https://github.com/Obsidian-StudiosInc/os-xtoo/files/1968487/build.log)

**Comment by wltjr** [comment]
Ah thanks, I was not clear on that. I forgot it had that use flag. Thanks for that I will correct now!
