### ISSUE TITLE
dev-db/firebird-2.5.5 : REQUIRED_USE

### ISSUE THREAD

**Issue by linuxunderground** [Obsidian-StudiosInc/os-xtoo#4]
REQUIRED_USE prevents SuperClassic install (line 170)

When I want SuperClassic, Portage says :
The following REQUIRED_USE flag constraints are unsatisfied:  
    exactly-one-of ( client superserver xinetd )

**Comment by wltjr** [comment]
Yeah I am not sure who added that. I think I recall someone asking me about it, and putting that in there. I have removed the REQUIRED_USE variable and value. I have not tested this, so let me know if you run into other issues and I will address them. I am onto 3.0, so only doing stuff with 2.5.x for others really. But no use flag should be super classic.

**Comment by wltjr** [comment]
In the years since I was a gentoo developer and officially maintained the package in tree, many Gentoo devs have touched the ebuild. Finally making sure it has proper love and maintenance again... :)

**Comment by linuxunderground** [comment]
OK for me !

2016-03-19 1:50 GMT+01:00 William L. Thomson Jr. notifications@github.com:

**Comment by wltjr** [comment]
I take it that the package compiled and you ended up with super classic as desired. If so will close this issue or you can. Just want to confirm.

**Comment by linuxunderground** [comment]
OK SuperClassic works.
Issue can be closed.

2016-03-19 23:24 GMT+01:00 William L. Thomson Jr. notifications@github.com
:

**Comment by wltjr** [comment]
Great thanks for confirming :)
