### ISSUE TITLE
dev-java/aqute-resolve: Fails to compile due to missing abstract override

### ISSUE THREAD

**Issue by wltjr** [Obsidian-StudiosInc/os-xtoo#49]
Need to fix the following compilation failure
```
src/biz/aQute/resolve/BndResolver.java:16: error: BndResolver is not abstract and does not override abstract method resolveDynamic(ResolveContext,Wiring,Requirement) in Resolver
public class BndResolver implements Resolver {
       ^
1 error
```

**Comment by fionera** [comment]
Is there a workaround?

**Comment by wltjr** [comment]
@fionera I just need to fix the change. I will work on that today. Midst of bumping Netbeans from rc1 to release. Just need to add the missing abstract method. Opened this as a reminder mostly.

**Comment by wltjr** [comment]
@fionera work around till I fix and push. You can apply [this](https://github.com/bndtools/bnd/commit/5c017544f69c9754e8eaaef785ddf318df5dcd7f#diff-91f16a48dfe12a5e7a3da32a07c81470) as a patch. Toss in ```/etc/portage/patches/dev-java/aqute-resolve/```. Any name with a ```.patch``` or ```.diff``` suffix.

**Comment by fionera** [comment]
Thanks :)

**Comment by wltjr** [comment]
Sure thing! I fixed the package, but cannot push till I finish my bump of netbeans or it will be partial and may cause other issues for anyone merging netbeans. Not that its really that usable. Still do not like pushing partial work. Though I can see about a rebase and push. When ever I do push this issue with auto close. The local patch will need to be removed, as that will cause it to fail again, double patching.
