### ISSUE TITLE
How to add this overlay ?

### ISSUE THREAD

**Issue by DraGiuS** [Obsidian-StudiosInc/os-xtoo#6]
I've tried with layman but it seems i can't add it, because i don't know the name.
Can you tell me how to add this ?

Thanks

**Comment by wltjr** [comment]
I need to see about an entry or something for Layman. I thought there was a way for it to use git repos. Let me look into that and I will follow back up with some useful information or link to instructions or something.

**Comment by wltjr** [comment]
Ok here you go. Just pick a location, or go with /usr/local
```
/etc/portage/repos.conf/os-xtoo.conf

[os-xtoo]
location = /usr/local/overlay/os-xtoo
sync-type = git
sync-uri = https://github.com/Obsidian-StudiosInc/os-xtoo.git
auto-sync = yes
```
https://wiki.gentoo.org/wiki//etc/portage/repos.conf#External_ebuild_repository

**Comment by wltjr** [comment]
Added the above to readme, should be resolved, closing.
