### ISSUE TITLE
openjfx-bin-11_pre23 Not found

### ISSUE THREAD

**Issue by blabno** [Obsidian-StudiosInc/os-xtoo#64]
Unable to download https://download.java.net/java/early_access/openjfx11/23/binaries/openjfx-11-ea+23_linux-x64_bin-sdk.zip

https://gluonhq.com/products/javafx/ shows 11-ea+25 only

**Comment by wltjr** [comment]
I need to bump that, I will do that today. Thanks!

**Comment by wltjr** [comment]
I need to bump that package, I will do that today. Thanks!

Github is acting funny...

**Comment by wltjr** [comment]
That takes care of the broken download. Still need to improve openjfx integration and usage, likely via some eclass stuff. Right now the 2 other packages using this, if installed, would need to be re-installed. Just for the symlink to be updated correctly. I slapped this package together quickly and it does need improvement.
