### ISSUE TITLE
ERROR: x11-wm/enlightenment-9999::os-xtoo failed (depend phase): >  epunt-cxx.eclass could not be found by inherit()

### ISSUE THREAD

**Issue by stephan--** [Obsidian-StudiosInc/os-xtoo#78]
Hi guys,

since todays emerge --sync im getting the following error when doing a sync:

>  * ERROR: x11-wm/enlightenment-9999::os-xtoo failed (depend phase):
>  *   epunt-cxx.eclass could not be found by inherit()
>  * 
>  * Call stack:
>  *                   ebuild.sh, line 609:  Called source '/usr/local/overlay/os-xtoo/x11-wm/enlightenment/enlightenment-9999.ebuild'
>  *   enlightenment-9999.ebuild, line  16:  Called inherit 'e'
>  *                   ebuild.sh, line 314:  Called __qa_source '/usr/local/overlay/os-xtoo/eclass/e.eclass'
>  *                   ebuild.sh, line 112:  Called source '/usr/local/overlay/os-xtoo/eclass/e.eclass'
>  *                    e.eclass, line 114:  Called inherit 'epunt-cxx' 'libtool'
>  *                   ebuild.sh, line 290:  Called die
>  * The specific snippet of code:
>  *   		[[ -z ${location} ]] && die "${1}.eclass could not be found by inherit()"

Any idea whats happening and how i could fix that?

**Comment by liquuid** [comment]
Same problem here

**Comment by wltjr** [comment]
Sorry about that, the issue is due to a legacy eclass that has been removed from tree. I removed usage and the inherit, that should fix the issue.
