### ISSUE TITLE
jem fails to build with enabled source useflag

### ISSUE THREAD

**Issue by Aison0** [Obsidian-StudiosInc/os-xtoo#79]
I tried to build jem with enabled source useflag and get this error:

> -- Installing: /var/tmp/portage/dev-java/jem-0.2.7/image/usr/share/man/man1/jem.1
> mkdir: cannot create directory ‘/var/tmp/portage/dev-java/jem-0.2.7/image//usr/share/jem/sources’: No such file or directory
>  * ERROR: dev-java/jem-0.2.7::os-xtoo failed (install phase):

I attached my [build.log](https://github.com/Obsidian-StudiosInc/os-xtoo/files/4521137/build.log)

**Comment by wltjr** [comment]
Thanks for the report, I will fix the issue right away.
